### ISSUE TITLE
Insufficient clearance on mounting holes

### ISSUE THREAD

**Issue by pdp7** [beagleboard/beaglev-starlight#10]
From @marckleinebudde in the [forum](http://forum.beagleboard.org/):
> the clearance on the raspi compatible mounting holes is not that great. Also having copper around the holes would be good, too.
![78d2df95a32b724e96fdf02cd6c63332d3d49eac](https://user-images.githubusercontent.com/313864/116475077-30770300-a82e-11eb-8534-159be17bdf92.jpeg)

**Comment by mitag** [comment]
As a workaround, you could perhaps replace the M 2.5 spacers with M 2 spacers and place a nylon washer underneath.

**Comment by FionaYu20180326** [comment]
> As a workaround, you could perhaps replace the M 2.5 spacers with M 2 spacers and place a nylon washer underneath.
Thanks for your feedback. This is a mounting hole compatible with raspberry pi. We will modify this design to move the chip.

**Comment by marckleinebudde** [comment]
It even works with the metal spacer. If I'm careful the spacer doesn't touch any pins of the chip. Just make sure it's fixed in the next board revision.
