### ISSUE TITLE
request for part information for KiCad conversion

### ISSUE THREAD

**Issue by pdp7** [beagleboard/beaglev-starlight#17]
@FionaYu20180326 would you be able to help @aswinvenu ?

He recreating the schematic in KiCad:
https://gitlab.com/aswinvenu/beaglev-kicad

He is trying to find information on:
1. UBF31-0171 - USB Type C connector from MTCONN
2. UAA111C-84161-4H - Dual Stacked USB3.0 Type A from FOXCONN
3. ST-HD-010 - HDMI connector from SHANQI
4. H9HCNNNCPUMLXR-NEE - 32Gb RAM from Hynix

This is also a post in the forum:
https://forum.beagleboard.org/t/beaglev-kicad/30006/6?u=drewfustini

**Comment by FionaYu20180326** [comment]
I asked aswinvenu to share email address to me on Beagleboard forum.

 

 

  _____  

Best Regards 

Fiona Yu (余凤)  Project Manager

Seeed Technology Co., Ltd.

TEL:  +86 -186 8870 1862

 

From: ***@***.*** ***@***.***> On Behalf Of Drew Fustini
Sent: 2021年6月11日 2:29
To: beagleboard/beaglev-starlight ***@***.***>
Cc: Fiona Yu ***@***.***>; Mention ***@***.***>
Subject: [beagleboard/beaglev-starlight] request for part information (#17)

 

@FionaYu20180326 <https://github.com/FionaYu20180326>  would you be able to help @aswinvenu <https://github.com/aswinvenu>  ?

He recreating the schematic in KiCad:
https://gitlab.com/aswinvenu/beaglev-kicad

He is trying to find information on:

1.  UBF31-0171 - USB Type C connector from MTCONN

2.  UAA111C-84161-4H - Dual Stacked USB3.0 Type A from FOXCONN

3.  ST-HD-010 - HDMI connector from SHANQI

4.  H9HCNNNCPUMLXR-NEE - 32Gb RAM from Hynix

This is also a post in the forum:
https://forum.beagleboard.org/t/beaglev-kicad/30006/6?u=drewfustini
